### PR TITLE
Confirm support for new DaVinci roles

### PR DESCRIPTION
**Pull request by patrickcping**
### Change Description

* `data-source/pingone_role`: Add DaVinci roles to the documentation examples.
* Expand `pingone_role` data source tests for retrieving new DaVinci roles (housekeeping)
* Expand `pingone_role_assignment_user` resource tests for assigning new DaVinci roles (housekeeping)

#### Testing Shell Command

```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run ^TestAccRoleDataSource_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```

#### Testing Results

```shell
=== RUN   TestAccRoleDataSource_ByNameFull
=== PAUSE TestAccRoleDataSource_ByNameFull
=== RUN   TestAccRoleDataSource_NotFound
=== PAUSE TestAccRoleDataSource_NotFound
=== CONT  TestAccRoleDataSource_ByNameFull
=== CONT  TestAccRoleDataSource_NotFound
--- PASS: TestAccRoleDataSource_NotFound (1.23s)
--- PASS: TestAccRoleDataSource_ByNameFull (33.84s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/base        34.319s
```

#### Testing Shell Command

```shell
TF_LOG= TF_LOG_PATH=`pwd`/output.log TF_ACC=1 go test -v -timeout 240s -run ^TestAccRoleAssignmentUser_ github.com/pingidentity/terraform-provider-pingone/internal/service/base
```

#### Testing Results

```shell
=== RUN   TestAccRoleAssignmentUser_Population
=== PAUSE TestAccRoleAssignmentUser_Population
=== RUN   TestAccRoleAssignmentUser_Organisation
=== PAUSE TestAccRoleAssignmentUser_Organisation
=== RUN   TestAccRoleAssignmentUser_Environment
=== PAUSE TestAccRoleAssignmentUser_Environment
=== CONT  TestAccRoleAssignmentUser_Population
=== CONT  TestAccRoleAssignmentUser_Environment
=== CONT  TestAccRoleAssignmentUser_Organisation
--- PASS: TestAccRoleAssignmentUser_Population (13.88s)
--- PASS: TestAccRoleAssignmentUser_Environment (77.84s)
--- PASS: TestAccRoleAssignmentUser_Organisation (79.58s)
PASS
ok      github.com/pingidentity/terraform-provider-pingone/internal/service/base        79.968s
```

### CODE REVIEW

**Comment by dbryar** [comment]
@patrickcping I've followed the example in the PR but the `plan` throws an error, even though the validation passes

```
╷
│ Error: Cannot find role DaVinci Admin
│ 
│   with data.pingone_role.da_vinci_admin,
│   on dev.tf line 498, in data "pingone_role" "da_vinci_admin":
│  498: data "pingone_role" "da_vinci_admin"{
│ 
╵
╷
│ Error: Cannot find role DaVinci Admin Read Only
│ 
│   with data.pingone_role.da_vinci_admin_read_only,
│   on dev.tf line 502, in data "pingone_role" "da_vinci_admin_read_only":
│  502: data "pingone_role" "da_vinci_admin_read_only"{
│ 
```

using the same/identical example in the PR

```hcl
data "pingone_role" "da_vinci_admin" {
  name = "DaVinci Admin"
}

data "pingone_role" "da_vinci_admin_read_only" {
  name = "DaVinci Admin Read Only"
}
```

On previous release `0.18.0`. I've updated the pipeline to `0.18.1` to confirm this is not version related, unless this only works in `0.19.0`?

**Comment by dbryar** [comment]
An API call to list all roles returns

```json
[
  {
    id: '1813bc13-8d13-4e88-a825-d40bfe82777b',
    name: 'Organization Admin',
    description: 'Organization Admin'
  },
  {
    id: '29ddce68-cd7f-4b2a-b6fc-f7a19553b496',
    name: 'Environment Admin',
    description: 'Environment Admin'
  },
  {
    id: '0bd9c966-7664-4ac1-b059-0ff9293908e2',
    name: 'Identity Data Admin',
    description: 'Identity Data Admin'
  },
  {
    id: 'b5057d0d-7281-47f6-9398-8a7e4cb71397',
    name: 'Client Application Developer',
    description: 'Client Application Developer'
  },
  {
    id: 'ce00e15f-f845-4df1-abf3-fdc4ff4e176c',
    name: 'Identity Data Read Only',
    description: 'Identity Data Read Only'
  },
  {
    id: '7aba580c-5ec7-4b26-987d-85f462767455',
    name: 'Configuration Read Only',
    description: 'Configuration Read Only'
  },
  {
    id: 'c65f13f5-f42c-4ffc-aa3a-4858d4ac3f6d',
    name: 'PingFederate Administrator',
    description: 'PingFederate Administrator'
  },
  {
    id: 'ec21ef32-0885-4210-8fe3-247bc2f40e7d',
    name: 'PingFederate Expression Administrator',
    description: 'PingFederate Expression Administrator'
  },
  {
    id: '03643153-e396-4c35-b527-ac05b43a64fb',
    name: 'PingFederate Crypto Administrator',
    description: 'PingFederate Crypto Administrator'
  },
  {
    id: '6f6793ad-4a5a-421b-8867-406ebee618de',
    name: 'PingFederate User Administrator',
    description: 'PingFederate User Administrator'
  },
  {
    id: 'b812ab8e-8fbc-45a9-b965-136849148040',
    name: 'PingFederate Auditor',
    description: 'PingFederate Auditor'
  },
  {
    id: '168d545c-8337-4a34-8426-9c173d60e331',
    name: 'DaVinci Admin',
    description: 'DaVinci Admin'
  },
  {
    id: 'e23fed81-8c98-4c20-b823-8d29514ab5f6',
    name: 'DaVinci Admin Read Only',
    description: 'DaVinci Admin Read Only'
  }
]
```

**Comment by patrickcping** [comment]
@dbryar You're correct, the provider needs a module update which will be in the next provider release (`v0.19.0`) because it's implemented as an ENUM for validation

One thing on my list is to review the ENUM strategy in the provider overall.  There is a balance between allowing items like this as "free-text" (automatically accepting new values as they are released on the API) and restricting them because the provider code may not expect certain values and needs adjustment based on new individual behaviours.

In this case, it could have accepted the new role values as-is, but there may be occasions in the future where a role may have special grantability rules that need extra provider code for.  I need to review over the coming weeks

**Comment by patrickcping** [comment]
So watchers of this change are aware, the general support of the DaVinci admin roles needs to be pushed into a later release.  This is because the roles cannot be re-granted from the worker app client that Terraform uses in the `provider {}` block.

The existing combinations of `Environment Admin` and `Identity Data Admin` will continue to work in the interim

Currently support for DaVinci admin roles is aligned to the `v0.20.0` release of the provider, but this can change.  If we have the ability to pull the release of the DaVinci admin roles forward then we will

**Comment by patrickcping** [comment]
The required changes to the API were made at the end of last week so we're able to include DaVinci role support in the `v0.19.0` release

**Pull request merged**
